---
#
# Ansible managed
#
repository:
  description: Install Hashicorp Vault, either a package or a binary.
  homepage: https://buluma.github.io/
  topics: vault, hashicorp, security, ansible, molecule, playbook
